// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/odoo-card-albaranes.tsx": () => import("../components/mockups/odoo-card-albaranes.tsx"),
  "./components/mockups/ventas-entrega.tsx": () => import("../components/mockups/ventas-entrega.tsx")
};
