import React, { useMemo, useState } from "react";
import { ArrowDownToLine, ArrowRight, ArrowRightLeft, Check, ChevronDown, ClipboardCheck, Clock3, Container, Gauge, Info, MapPin, Package, RefreshCw, Search, ShieldCheck, TriangleAlert, Truck, Weight, X } from "lucide-react";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Input } from "../ui/input";
import { Progress } from "../ui/progress";

type Transfer = { ref: string; from: string; to: string; route: string; status: "Listo para planificar" | "Revisión requerida"; weight: number | null; weightSource: "Odoo" | "Estimado" | "Sin medición"; volume: number | null; lines: number };
const transfers: Transfer[] = [
  { ref: "Urbin/INT/00070", from: "Urbina", to: "Lechería", route: "CCS → LCH", status: "Listo para planificar", weight: 184.6, weightSource: "Odoo", volume: 1.28, lines: 7 },
  { ref: "Urbin/INT/00068", from: "Urbina", to: "Maracay", route: "CCS → MYC", status: "Listo para planificar", weight: 96, weightSource: "Estimado", volume: 0.74, lines: 4 },
  { ref: "Urbin/INT/00061", from: "Lechería", to: "Urbina", route: "LCH → CCS", status: "Revisión requerida", weight: null, weightSource: "Sin medición", volume: null, lines: 2 },
  { ref: "Urbin/INT/00057", from: "Urbina", to: "Valencia", route: "CCS → VLC", status: "Listo para planificar", weight: 412.8, weightSource: "Odoo", volume: 2.96, lines: 12 },
  { ref: "Urbin/INT/00049", from: "Maracay", to: "Urbina", route: "MYC → CCS", status: "Revisión requerida", weight: 72, weightSource: "Estimado", volume: null, lines: 3 },
];
const vehicles = [
  { name: "JAC HFC 1035K", plate: "A81AB4D", capacity: 3500, volume: 14, recommended: true },
  { name: "Mitsubishi Canter", plate: "B62CD8E", capacity: 2500, volume: 9, recommended: false },
  { name: "Ford Cargo 815", plate: "C45EF2G", capacity: 8000, volume: 32, recommended: false },
];
function SourceBadge({ source }: { source: Transfer["weightSource"] }) {
  const styles = source === "Odoo" ? "border-sky-400/30 bg-sky-400/10 text-sky-300" : source === "Estimado" ? "border-amber-400/30 bg-amber-400/10 text-amber-300" : "border-rose-400/30 bg-rose-400/10 text-rose-300";
  return <span className={`inline-flex rounded px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide ${styles}`}>{source}</span>;
}
function Metric({ label, value, detail, icon: Icon, tone = "text-foreground" }: { label: string; value: string; detail: string; icon: React.ElementType; tone?: string }) {
  return <div className="rounded-lg border border-border/70 bg-card/70 p-3 transition-colors hover:border-primary/40"><div className="flex items-center justify-between text-muted-foreground"><span className="text-[10px] font-semibold uppercase tracking-[0.14em]">{label}</span><Icon className="h-4 w-4 text-primary/80" /></div><div className={`mt-1 text-xl font-semibold tracking-tight ${tone}`}>{value}</div><div className="mt-0.5 text-[11px] text-muted-foreground">{detail}</div></div>;
}
export default function PreDespachoTrasladosPreview() {
  const [query, setQuery] = useState("");
  const [selectedRef, setSelectedRef] = useState("Urbin/INT/00070");
  const [planned, setPlanned] = useState(false);
  const [showDetails, setShowDetails] = useState(true);
  const [toast, setToast] = useState("");
  const filtered = useMemo(() => transfers.filter(t => `${t.ref} ${t.from} ${t.to}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const selected = transfers.find(t => t.ref === selectedRef) ?? transfers[0];
  function planTransfer() { setPlanned(true); setToast(`Plan de carga preparado para ${selected.ref}`); window.setTimeout(() => setToast(""), 2600); }
  return <div className="dark min-h-screen bg-[#10181c] text-foreground selection:bg-primary/30">
    <div className="pointer-events-none fixed inset-0 opacity-[0.035]" style={{ backgroundImage: "linear-gradient(rgba(255,255,255,.5) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.5) 1px, transparent 1px)", backgroundSize: "24px 24px" }} />
    <div className="relative mx-auto max-w-[1540px] space-y-4 p-4 lg:p-6">
      <header className="flex flex-wrap items-end justify-between gap-4 border-b border-border/70 pb-4"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-semibold uppercase tracking-[0.18em] text-primary"><ArrowRightLeft className="h-4 w-4" /> Operaciones / Pre-Despacho</div><h1 className="text-2xl font-semibold tracking-tight">Planificación de traslados</h1><p className="mt-1 text-sm text-muted-foreground">Revisa medidas, valida compatibilidad y deja el despacho listo para asignación.</p></div><div className="flex items-center gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="h-2 w-2 rounded-full bg-emerald-400" /> Odoo sincronizado hace 4 min</span><Button variant="outline" size="sm" className="gap-2 border-border/80 bg-card/40"><RefreshCw className="h-3.5 w-3.5" /> Actualizar</Button></div></header>
      <div className="grid gap-3 md:grid-cols-4"><Metric label="Pendientes" value="12" detail="7 cruzan plaza" icon={ClipboardCheck} /><Metric label="Medidas completas" value="8 / 12" detail="Peso y volumen disponibles" icon={ShieldCheck} tone="text-emerald-300" /><Metric label="Revisión requerida" value="4" detail="Sin medición o dato parcial" icon={TriangleAlert} tone="text-amber-300" /><Metric label="Ventana de salida" value="Hoy · 16:30" detail="Corte de planificación" icon={Clock3} /></div>
      <div className="grid gap-4 xl:grid-cols-[minmax(0,1.3fr)_minmax(460px,0.8fr)]">
        <Card className="overflow-hidden border-border/80 bg-card/75 shadow-2xl shadow-black/10">
          <CardHeader className="border-b border-border/70 px-4 py-3">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div><CardTitle className="text-base">Traslados por planificar</CardTitle><p className="mt-0.5 text-xs text-muted-foreground">Solo movimientos entre plazas que todavía no tienen despacho activo.</p></div>
              <div className="relative w-full sm:w-64"><Search className="absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Buscar referencia o plaza" className="h-8 border-border/70 bg-background/60 pl-8 text-xs" /></div>
            </div>
            <div className="flex flex-wrap gap-2 pt-2"><Badge variant="secondary" className="bg-primary/10 text-primary">Todos · 12</Badge><Badge variant="outline" className="border-border/80">Cruza Plaza · 7</Badge><Badge variant="outline" className="border-border/80">Con alertas · 4</Badge></div>
          </CardHeader>
          <CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-muted/20 text-[10px] uppercase tracking-[0.12em] text-muted-foreground"><tr className="border-b border-border/60"><th className="px-4 py-2.5 font-semibold">Referencia</th><th className="px-3 py-2.5 font-semibold">Ruta</th><th className="px-3 py-2.5 font-semibold">Peso</th><th className="px-3 py-2.5 font-semibold">Volumen</th><th className="px-3 py-2.5 font-semibold">Estado</th></tr></thead><tbody>{filtered.map(t => <tr key={t.ref} onClick={() => { setSelectedRef(t.ref); setPlanned(false); }} className={`cursor-pointer border-b border-border/40 transition-colors hover:bg-primary/[0.07] ${selectedRef === t.ref ? "bg-primary/[0.09] shadow-[inset_3px_0_0_hsl(var(--primary))]" : ""}`}><td className="px-4 py-3"><div className="font-semibold">{t.ref}</div><div className="mt-0.5 text-[11px] text-muted-foreground">{t.lines} líneas · <span className="text-primary/80">Cruza Plaza</span></div></td><td className="whitespace-nowrap px-3 py-3"><div className="flex items-center gap-1.5"><span>{t.from}</span><ArrowRight className="h-3 w-3 text-muted-foreground" /><span>{t.to}</span></div><div className="mt-0.5 font-mono text-[10px] text-muted-foreground">{t.route}</div></td><td className="whitespace-nowrap px-3 py-3"><div className={t.weight !== null ? "font-medium" : "italic text-muted-foreground"}>{t.weight !== null ? `${t.weight} kg` : "sin medición"}</div><div className="mt-1"><SourceBadge source={t.weightSource} /></div></td><td className="whitespace-nowrap px-3 py-3">{t.volume !== null ? `${t.volume} m³` : <span className="italic text-muted-foreground">sin dato</span>}</td><td className="px-3 py-3"><Badge variant="outline" className={t.status === "Listo para planificar" ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : "border-amber-400/30 bg-amber-400/10 text-amber-300"}>{t.status}</Badge></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border/60 px-4 py-2.5 text-[11px] text-muted-foreground"><span>Mostrando {filtered.length} de 12 traslados</span><span className="inline-flex items-center gap-1"><Info className="h-3 w-3" /> Ordenado por fecha de salida</span></div></CardContent>
        </Card>
         <Card className="overflow-hidden border-primary/25 bg-card/80 shadow-2xl shadow-black/10"><CardHeader className="border-b border-border/70 px-5 py-3"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] font-semibold uppercase tracking-[0.16em] text-primary">Traslado seleccionado</div><CardTitle className="mt-1 text-xl">{selected.ref}</CardTitle></div><Badge className="border border-primary/30 bg-primary/10 text-primary">Cruza Plaza</Badge></div><div className="mt-3 grid grid-cols-[1fr_auto_1fr] items-center gap-3 rounded-lg border border-border/70 bg-background/30 p-3"><div><div className="flex items-center gap-1 text-[10px] uppercase tracking-wide text-muted-foreground"><MapPin className="h-3 w-3" /> Origen</div><div className="mt-1 font-semibold">{selected.from}</div><div className="font-mono text-[10px] text-muted-foreground">CCS-01 · Urbina</div></div><div className="flex flex-col items-center gap-1 text-primary"><ArrowRight className="h-5 w-5" /><span className="font-mono text-[9px] text-muted-foreground">{selected.route}</span></div><div><div className="flex items-center gap-1 text-[10px] uppercase tracking-wide text-muted-foreground"><MapPin className="h-3 w-3" /> Destino</div><div className="mt-1 font-semibold">{selected.to}</div><div className="font-mono text-[10px] text-muted-foreground">LCH-01 · Lechería</div></div></div></CardHeader>
          <CardContent className="space-y-4 p-5"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-sky-400/20 bg-sky-400/[0.06] p-3"><div className="flex items-center justify-between text-[10px] uppercase tracking-wide text-muted-foreground"><span>Peso efectivo</span><Weight className="h-3.5 w-3.5 text-sky-300" /></div><div className="mt-1 text-lg font-semibold">{selected.weight !== null ? `${selected.weight} kg` : "sin medición"}</div><div className="mt-1"><SourceBadge source={selected.weightSource} /></div></div><div className="rounded-lg border border-border/70 bg-background/25 p-3"><div className="flex items-center justify-between text-[10px] uppercase tracking-wide text-muted-foreground"><span>Volumen calculado</span><Container className="h-3.5 w-3.5 text-primary" /></div><div className="mt-1 text-lg font-semibold">{selected.volume !== null ? `${selected.volume} m³` : "sin dato"}</div><div className="mt-1 text-[10px] text-muted-foreground">{selected.volume !== null ? "Desde líneas de traslado" : "Requiere dimensión de artículo"}</div></div></div>
             {selected.weightSource === "Sin medición" || selected.volume === null ? <div className="flex gap-2 rounded-lg border border-amber-400/25 bg-amber-400/[0.07] p-3 text-xs text-amber-200"><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0 text-amber-300" /><div><div className="font-semibold">Medición incompleta · planificación permitida</div><div className="mt-0.5 text-amber-100/70">La compatibilidad se mostrará como parcial. La medición faltante no bloquea la planificación; puedes completar el dato en Odoo o registrar una estimación después.</div></div></div> : <div className="flex gap-2 rounded-lg border border-emerald-400/20 bg-emerald-400/[0.06] p-3 text-xs text-emerald-200"><Check className="mt-0.5 h-4 w-4 shrink-0" /><div><div className="font-semibold">Medidas listas para planificar</div><div className="mt-0.5 text-emerald-100/70">Peso validado desde Odoo. El volumen se calculó con las líneas recibidas.</div></div></div>}
            <div className="rounded-lg border border-border/70"><button type="button" onClick={() => setShowDetails(!showDetails)} className="flex w-full items-center justify-between px-3 py-2.5 text-left text-sm font-semibold transition-colors hover:bg-muted/20"><span className="flex items-center gap-2"><Package className="h-4 w-4 text-primary" /> Detalle de carga <span className="text-[11px] font-normal text-muted-foreground">7 líneas</span></span><ChevronDown className={`h-4 w-4 transition-transform ${showDetails ? "rotate-180" : ""}`} /></button>{showDetails && <div className="border-t border-border/60 px-3 pb-3"><div className="grid grid-cols-[1fr_auto_auto] gap-2 py-2 text-[10px] uppercase tracking-wide text-muted-foreground"><span>Artículo</span><span>Cant.</span><span>Peso</span></div><div className="space-y-2 text-xs"><div className="grid grid-cols-[1fr_auto_auto] gap-2 border-t border-border/40 pt-2"><span className="font-medium">ONT SUMEC Navigator T21 con CATV<div className="font-mono text-[10px] text-muted-foreground">NTS050036</div></span><span>5</span><span>82.0 kg</span></div><div className="grid grid-cols-[1fr_auto_auto] gap-2 border-t border-border/40 pt-2"><span className="font-medium">Monitor industrial 24"<div className="font-mono text-[10px] text-muted-foreground">MON-2401</div></span><span>2</span><span>102.6 kg</span></div></div></div>}</div>
            <div className="border-t border-border/60 pt-3"><div className="mb-2 flex items-center justify-between"><div><div className="text-sm font-semibold">Compatibilidad directa de flota</div><div className="text-[11px] text-muted-foreground">Ordenada por ajuste más preciso · sin pasos intermedios</div></div><Gauge className="h-5 w-5 text-primary" /></div>{vehicles.map(v => { const pct = Math.round((selected.weight ?? 0) / v.capacity * 100); return <div key={v.plate} className={`mb-2 rounded-lg border p-2.5 transition-colors hover:border-primary/40 ${v.recommended ? "border-primary/40 bg-primary/[0.06]" : "border-border/60 bg-background/20"}`}><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><Truck className="h-4 w-4 text-muted-foreground" /><span className="text-xs font-semibold">{v.name}</span>{v.recommended && <Badge className="h-5 bg-primary text-primary-foreground text-[10px]">Sugerido</Badge>}</div><span className="font-mono text-[10px] text-muted-foreground">{v.plate}</span></div><div className="mt-2 flex items-center gap-2"><Progress value={pct} className="h-1.5 flex-1" /><span className="w-10 text-right text-[10px] text-muted-foreground">{pct}% kg</span><span className="text-[10px] text-muted-foreground">/ {v.volume} m³</span></div></div> })}</div>
             <div className="flex gap-2 pt-1"><Button className="flex-1 gap-2 shadow-lg shadow-primary/10" onClick={planTransfer}><Truck className="h-4 w-4" /> {planned ? "Plan preparado" : "Planificar con flota compatible"}</Button><Button variant="outline" size="icon" className="border-border/80" title="Cerrar selección" onClick={() => setSelectedRef("")}><X className="h-4 w-4" /></Button></div>{(selected.weight === null || selected.volume === null) && <p className="text-center text-[11px] text-amber-300">La planificación permanece habilitada con datos parciales.</p>}</CardContent></Card>
      </div>
      <div className="flex items-center justify-between rounded-lg border border-border/60 bg-card/40 px-4 py-2.5 text-[11px] text-muted-foreground"><span className="inline-flex items-center gap-2"><ArrowDownToLine className="h-3.5 w-3.5 text-primary" /> Los pesos etiquetados como Odoo son de solo lectura y reflejan la última sincronización.</span><span>Vista de verificación · sin conexión a datos reales</span></div>
      {toast && <div className="fixed bottom-5 right-5 rounded-lg border border-emerald-400/30 bg-[#162921] px-4 py-3 text-xs text-emerald-200 shadow-xl"><Check className="mr-2 inline h-4 w-4" />{toast}</div>}
    </div>
  </div>;
}